services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.simple
        container_name: garage-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        networks:
            - garage-network

    db:
        image: mysql:8.0
        container_name: garage-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: garage_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: secret
            MYSQL_USER: garage_user
        volumes:
            - dbdata:/var/lib/mysql/
        ports:
            - "3307:3306"
        networks:
            - garage-network

networks:
    garage-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
